### ISSUE TITLE
SearchEngine module

### ISSUE THREAD

**Issue by awebc** [trntv/yii2-starter-kit#427] opened 2016-05-28 13:18 UTC
hi, dear
May be you can add a SearchEngine module ( about sphinx or elasticSearch)

a solution about SearchEngine to the content of website

**Comment by yanhuixie** [comment] 2016-06-06 13:56
Hi~ 
As far as I know, a SearchEngine is an independent service, you should deploy it separately.
And a set of client APIs of several search engines are shipped with yii2.
for example:
[yiisoft/yii2-elasticsearch](https://github.com/yiisoft/yii2-elasticsearch)
[yiisoft/yii2-sphinx](https://github.com/yiisoft/yii2-sphinx)

**Comment by davidjeddy** [comment] 2017-10-18 15:31
Duplicate of #338.

**Closed** 2017-12-19 15:52 UTC
Labels: enhancement
