### ISSUE TITLE
Feature Request: Add web interface for RBAC administration

### ISSUE THREAD

**Issue by senguttuvang** [trntv/yii2-starter-kit#414] opened 2016-05-03 01:25 UTC

**Comment by yanhuixie** [comment] 2016-05-05 08:34
You may simply composer require "mdmsoft/yii2-admin": "^2.5"?

**Comment by senguttuvang** [comment] 2016-05-05 08:37
That's what I did now. But I doubt whether that extension and this starterkit are compatible.

**Comment by yanhuixie** [comment] 2016-05-05 09:12
As I know, both yii2-starter-kit (access control part) and mdmsoft/yii2-admin implements the standard yii2 rbac interfaces.
Just follow mdmsoft/yii2-admin installation instruction and usage documentation, try it. :-)

**Comment by desaikalpesh34** [comment] 2016-09-26 05:11
@yanhuixie 
i have tried this [https://github.com/desaikalpesh34/yii2-kit](https://github.com/desaikalpesh34/yii2-kit) here

**Comment by davidjeddy** [comment] 2017-12-01 13:00
Duplicate of https://github.com/trntv/yii2-starter-kit/issues/325
PR available https://github.com/trntv/yii2-starter-kit/pull/586

**Comment by dungphanxuan** [comment] 2017-12-04 04:36
My case not need RBAC interface, because when design system, all info about RBAC will description detal, so you need config once at first time.

**Comment by trntv** [comment] 2017-12-19 14:09
https://github.com/trntv/yii2-starter-kit/pull/586

**Closed by trntv** 2017-12-19 14:09 UTC
